version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-temp-email-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILSAC_API_KEY=${MAILSAC_API_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DEBUG=false
      - LOG_LEVEL=INFO
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge